#!/bin/bash
# script to print nums from 1 to 100
# if the num devisable by 3 and 5 print FizzBuzz
# if the num is devisable by 3 print Fizz
# if the num is devisable by 5 print Buzz

i=1
while [ $i -le 100 ]
do
    if [ $((i % 15)) -eq 0 ]
    then
        echo "FizzBuzz"
    elif [ $((i % 3)) -eq 0 ]
    then
        echo "Fizz"
    elif [ $((i % 5)) -eq 0 ]
    then
        echo "Buzz"
    else
        echo "$i"
    fi
    (( i++ ))
    
done
